name: Deploy to Github Pages

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: mkdocs build
      run: |
        pip freeze
        pip --version
        python --version
        mkdocs --version
        mkdocs build --verbose --clean --strict

    - name: Deploy if main
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
